name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: "mongodb+srv://cluster0.cu2ye.mongodb.net/solardb"
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

  

jobs:
    unit-testing:
        name: Unit Testing

        strategy:
          matrix:
            node-version: [20.x]
        runs-on: ${{ matrix.node-version }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v4
          with:
            node-version: 20
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: node test
          if: success()
          
        # - name: Archive Test Result
        #   uses: actions/upload-artifact@v4
        #   with:
        #     name: Mocha-Test-Result
        #     path: test-results.xml